/* test-registration
{
  "name": "Comms attachment upload thumbnails — 600px webp generated + thumbnail_key persisted, no enlargement, non-image and undecodable-image fallbacks, end-to-end thumb serve (member 200 / non-member 403), backfill drain convergence + prod-action registration (Tasks #3318/#3421)",
  "regression": true,
  "smoke": true,
  "smokeReason": "Task #3318: attachment upload thumbnail generation (POST upload route) — 600px-wide webp thumbnail generated + thumbnail_key persisted for images, no enlargement for small images, single upload + NULL thumbnail_key for non-images, and best-effort fallback (201, NULL key) when sharp cannot decode. Also serves the actually-uploaded thumbnail key end-to-end (member 200 webp, non-member 403). Object storage is prototype-stubbed; per-run random-suffixed seeds.",
  "tier": "small"
}
test-registration */
/**
 * Attachment upload thumbnail generation — POST /api/comms/channels/:id/messages/upload.
 *
 * tests/comms-attachment-serving.test.ts covers the GET serving side of
 * thumbnails (thumbnail_key lookup + ACL). This test covers the write side:
 * the upload route must generate a downscaled webp thumbnail for resizable
 * image types, persist thumbnail_key on the attachment row, and degrade
 * gracefully (thumbnail_key NULL, upload still succeeds) for non-image files
 * and for image payloads sharp cannot decode.
 *
 * Verifies:
 *   - Large PNG upload → two storage uploads (original + thumb/ webp), the
 *     thumbnail is a real webp downscaled to 600px wide, and the attachment
 *     row's thumbnail_key matches the uploaded thumb key
 *   - Small PNG (< 600px) → thumbnail generated without enlargement
 *   - Non-image (PDF) upload → single storage upload, thumbnail_key NULL
 *   - Corrupt bytes claiming image/png → upload still 201, thumbnail_key NULL
 *     (best-effort fallback, no 500)
 *   - Backfill (Task #3421): non-fast-list image/* rows are attempted (heic
 *     stamped, missing-original skipped with a logged reason) and the drain
 *     converges to zero pending
 *   - End-to-end serve: the thumbnail key produced by a real upload is served
 *     back via GET /api/comms/attachments/<thumbnailKey> to a channel member
 *     (200, webp, exact generated bytes), while a non-member gets 403
 *
 * Object storage is stubbed by patching ObjectStorageService.prototype, so no
 * real storage calls escape the test. sharp runs for real (it is the code
 * under test on the generation side and the decoder on the assertion side).
 */

import assert from "node:assert/strict";
import { randomBytes } from "node:crypto";
import express from "express";
import type { AddressInfo } from "node:net";
import * as undici from "undici";
import { eq, inArray, like, or } from "drizzle-orm";
import sharp from "sharp";

process.env.NODE_ENV = process.env.NODE_ENV || "test";

import { db, closeDbPools } from "../server/db";
import { users } from "@shared/schema";
import {
  commsChannels,
  commsChannelMembers,
  commsAttachments,
} from "../shared/models/comms";
import { ObjectStorageService } from "../server/replit_integrations/object_storage/objectStorage";
import { registerCommsRoutes } from "../server/routes/comms";
import { commsMessages } from "../shared/models/comms";
import {
  countPendingThumbnailBackfill,
  processThumbnailBackfillChunk,
  getThumbnailBackfillSkippedCount,
  __resetThumbnailBackfillSkipsForTest,
  COMMS_THUMBNAIL_BACKFILL_CHUNK,
} from "../server/services/commsAttachmentThumbnailBackfill";

const RUN = randomBytes(4).toString("hex");
const MEMBER_ID = `comms-thumb-up-${RUN}`;
const OUTSIDER_ID = `comms-thumb-out-${RUN}`;

// ─── Object storage stub (prototype patch — no real storage calls) ──────────
// Captures every uploaded object so the test can decode the thumbnail bytes.
const uploadedObjects = new Map<string, { buffer: Buffer; contentType: string }>();

(ObjectStorageService.prototype as any).streamUploadToPrivateKey = async function (
  objectKey: string,
  stream: NodeJS.ReadableStream,
  contentType: string,
) {
  const chunks: Buffer[] = [];
  for await (const chunk of stream as any) {
    chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
  }
  uploadedObjects.set(objectKey, { buffer: Buffer.concat(chunks), contentType });
};

// Serving-side stubs backed by the same captured-uploads map, so the GET
// attachment route serves exactly what the upload route stored.
(ObjectStorageService.prototype as any).getPrivateObjectFileByKey = async function (
  objectKey: string,
) {
  if (!uploadedObjects.has(objectKey)) throw new Error(`object not found: ${objectKey}`);
  return {
    __stubKey: objectKey,
    download: async () => [uploadedObjects.get(objectKey)!.buffer] as [Buffer],
  };
};
(ObjectStorageService.prototype as any).downloadObject = async function (
  file: any,
  res: express.Response,
) {
  const obj = uploadedObjects.get(file.__stubKey)!;
  res.set({ "Content-Type": obj.contentType, "Content-Length": String(obj.buffer.length) });
  res.status(200).end(obj.buffer);
};

// ─── Test app harness ────────────────────────────────────────────────────────
function makeApp(actingUserId: string): express.Express {
  const app = express();
  app.use(express.json());
  app.use((req: any, _res, next) => {
    // Clerk test seam (server/middlewares/requireAuth.ts): authenticates as
    // this user id; requireAuth resolves the real seeded users row and
    // populates req.user. (The pre-Clerk passport-shape injection stopped
    // working when auth migrated.)
    req.__test_clerkUserId = actingUserId;
    next();
  });
  registerCommsRoutes(app);
  return app;
}

// ─── Seed data ───────────────────────────────────────────────────────────────
const seedUserIds: string[] = [];
const seedChannelIds: string[] = [];
let channelId = "";

async function seed(): Promise<void> {
  await db
    .insert(users)
    .values({
      id: MEMBER_ID,
      username: MEMBER_ID,
      email: `${MEMBER_ID}@test.invalid`,
      firstName: "Thumb",
      lastName: "Upload",
      role: "account_manager",
    })
    .onConflictDoNothing();
  seedUserIds.push(MEMBER_ID);

  await db
    .insert(users)
    .values({
      id: OUTSIDER_ID,
      username: OUTSIDER_ID,
      email: `${OUTSIDER_ID}@test.invalid`,
      firstName: "Thumb",
      lastName: "Outsider",
      role: "account_manager",
    })
    .onConflictDoNothing();
  seedUserIds.push(OUTSIDER_ID);

  const [channel] = await db
    .insert(commsChannels)
    .values({
      name: `thumb-up-${RUN}`,
      slug: `thumb-up-${RUN}`,
      type: "channel",
      visibility: "private",
      createdBy: MEMBER_ID,
    })
    .returning();
  channelId = channel.id;
  seedChannelIds.push(channel.id);

  await db.insert(commsChannelMembers).values({
    channelId: channel.id,
    userId: MEMBER_ID,
    role: "member",
  });
}

process.on("exit", async () => {
  // Channel delete cascades to members, messages, and attachments.
  if (seedChannelIds.length > 0) {
    await db.delete(commsChannels).where(inArray(commsChannels.id, seedChannelIds)).catch(() => {});
  }
  if (seedUserIds.length > 0) {
    await db.delete(users).where(inArray(users.id, seedUserIds)).catch(() => {});
  }
  await closeDbPools();
});

// ─── Helpers ─────────────────────────────────────────────────────────────────

async function uploadFile(
  baseUrl: string,
  filename: string,
  contentType: string,
  bytes: Buffer,
): Promise<{ statusCode: number; body: any }> {
  const form = new undici.FormData();
  form.append("file", new Blob([new Uint8Array(bytes)], { type: contentType }), filename);
  form.append("content", `upload test ${filename}`);
  const res = await undici.request(
    `${baseUrl}/api/comms/channels/${channelId}/messages/upload`,
    { method: "POST", body: form },
  );
  const body: any = await res.body.json();
  return { statusCode: res.statusCode, body };
}

async function getAttachmentRow(id: string) {
  const [row] = await db
    .select()
    .from(commsAttachments)
    .where(eq(commsAttachments.id, id));
  return row;
}

// ─── Tests ───────────────────────────────────────────────────────────────────

(async () => {
  await seed();

  const app = makeApp(MEMBER_ID);
  const server = app.listen(0, "127.0.0.1");
  await new Promise<void>((resolve) => server.once("listening", resolve));
  const { port } = server.address() as AddressInfo;
  const base = `http://127.0.0.1:${port}`;

  let uploadedThumbKey: string | null = null;

  try {
    // (A) Large PNG → original + 600px-wide webp thumbnail, row has thumbnail_key
    {
      const bigPng = await sharp({
        create: { width: 1600, height: 900, channels: 3, background: { r: 180, g: 30, b: 60 } },
      })
        .png()
        .toBuffer();
      const before = uploadedObjects.size;
      const { statusCode, body } = await uploadFile(base, "big.png", "image/png", bigPng);
      assert.equal(statusCode, 201, "(A) upload should 201");
      assert.ok(body.attachment?.id, "(A) attachment returned");
      assert.equal(
        uploadedObjects.size - before,
        2,
        "(A) exactly two storage uploads (original + thumbnail)",
      );

      const row = await getAttachmentRow(body.attachment.id);
      assert.ok(row, "(A) attachment row persisted");
      assert.ok(row.thumbnailKey, "(A) thumbnail_key must be set for a large PNG");
      assert.ok(
        row.thumbnailKey!.startsWith("comms-attachments/thumb/") &&
          row.thumbnailKey!.endsWith(".webp"),
        `(A) thumbnail key shape: ${row.thumbnailKey}`,
      );
      uploadedThumbKey = row.thumbnailKey!;
      assert.notEqual(row.thumbnailKey, row.objectKey, "(A) thumb key differs from original");

      const original = uploadedObjects.get(row.objectKey);
      assert.ok(original?.buffer.equals(bigPng), "(A) original bytes stored untouched");

      const thumb = uploadedObjects.get(row.thumbnailKey!);
      assert.ok(thumb, "(A) thumbnail object uploaded under the recorded key");
      assert.equal(thumb!.contentType, "image/webp", "(A) thumbnail content type is webp");
      const meta = await sharp(thumb!.buffer).metadata();
      assert.equal(meta.format, "webp", "(A) thumbnail decodes as webp");
      assert.equal(meta.width, 600, "(A) thumbnail downscaled to 600px wide");
      assert.ok(
        thumb!.buffer.length < bigPng.length,
        "(A) thumbnail is smaller than the original",
      );
      console.log("  ✓ large PNG upload stores a 600px-wide webp thumbnail + thumbnail_key");
    }

    // (B) Small PNG (< 600px) → thumbnail generated without enlargement
    {
      const smallPng = await sharp({
        create: { width: 320, height: 200, channels: 3, background: { r: 20, g: 90, b: 160 } },
      })
        .png()
        .toBuffer();
      const { statusCode, body } = await uploadFile(base, "small.png", "image/png", smallPng);
      assert.equal(statusCode, 201, "(B) upload should 201");
      const row = await getAttachmentRow(body.attachment.id);
      assert.ok(row.thumbnailKey, "(B) small image still gets a thumbnail_key");
      const thumb = uploadedObjects.get(row.thumbnailKey!);
      assert.ok(thumb, "(B) thumbnail uploaded");
      const meta = await sharp(thumb!.buffer).metadata();
      assert.equal(meta.width, 320, "(B) small image must not be enlarged");
      console.log("  ✓ small PNG thumbnail is not enlarged (withoutEnlargement)");
    }

    // (C) Non-image (PDF) → single upload, thumbnail_key NULL
    {
      const pdfBytes = Buffer.from(`%PDF-1.4 fake ${RUN}`);
      const before = uploadedObjects.size;
      const { statusCode, body } = await uploadFile(base, "doc.pdf", "application/pdf", pdfBytes);
      assert.equal(statusCode, 201, "(C) upload should 201");
      assert.equal(
        uploadedObjects.size - before,
        1,
        "(C) exactly one storage upload for a non-image",
      );
      const row = await getAttachmentRow(body.attachment.id);
      assert.equal(row.thumbnailKey, null, "(C) thumbnail_key NULL for non-image");
      console.log("  ✓ non-image upload skips thumbnail generation (thumbnail_key NULL)");
    }

    // (D) Corrupt bytes claiming image/png → 201, thumbnail_key NULL (no 500)
    {
      const corrupt = Buffer.from(`not-actually-a-png-${RUN}`);
      const { statusCode, body } = await uploadFile(base, "broken.png", "image/png", corrupt);
      assert.equal(statusCode, 201, "(D) corrupt image must still 201 (best-effort thumbnail)");
      const row = await getAttachmentRow(body.attachment.id);
      assert.ok(row, "(D) attachment row persisted despite thumbnail failure");
      assert.equal(row.thumbnailKey, null, "(D) thumbnail_key NULL when sharp cannot decode");
      const original = uploadedObjects.get(row.objectKey);
      assert.ok(original?.buffer.equals(corrupt), "(D) original bytes still stored");
      console.log("  ✓ undecodable image falls back to full-res (201, thumbnail_key NULL)");
    }

    // (E) Backfill (Task #3421) — a NON-fast-list image/* MIME row is
    // ATTEMPTED (not silently pre-filtered): a decodable image/heic row is
    // stamped, and a row whose original is missing is skipped WITH a
    // logged reason (skip set), so the drain converges.
    // Download-side storage is served by the top-level
    // getPrivateObjectFileByKey stub (backed by the same captured-uploads
    // map, throws for unknown keys like real storage).
    {
      __resetThumbnailBackfillSkipsForTest();

      // Prune this test's own litter from PRIOR runs before seeding. The two
      // seeds below are never deleted afterwards (the skip set is in-process
      // only), so every past run left rows behind; combined with sibling
      // suites' uploads the shared-table backlog eventually outgrew the old
      // fixed 50-chunk drain cap and broke convergence for every later run
      // (memory: admin-audit count test saturation — prune per-scope at
      // start). The backfill-heic-/backfill-missing- key shapes are
      // exclusively this test's.
      await db
        .delete(commsAttachments)
        .where(
          or(
            like(commsAttachments.objectKey, "comms-attachments/backfill-heic-%"),
            like(commsAttachments.objectKey, "comms-attachments/backfill-missing-%"),
          ),
        );

      const decodablePng = await sharp({
        create: { width: 900, height: 500, channels: 3, background: { r: 40, g: 140, b: 90 } },
      })
        .png()
        .toBuffer();
      const heicKey = `comms-attachments/backfill-heic-${RUN}.heic`;
      uploadedObjects.set(heicKey, { buffer: decodablePng, contentType: "image/heic" });
      const missingKey = `comms-attachments/backfill-missing-${RUN}.img`;

      const [msg] = await db
        .insert(commsMessages)
        .values({ channelId, senderId: MEMBER_ID, content: `backfill seed ${RUN}` })
        .returning();
      const inserted = await db
        .insert(commsAttachments)
        .values([
          {
            messageId: msg.id,
            uploadedBy: MEMBER_ID,
            objectKey: heicKey,
            filename: "old-photo.heic",
            contentType: "image/heic", // NOT in RESIZABLE_IMAGE_TYPES — must still be attempted
            thumbnailKey: null,
          },
          {
            messageId: msg.id,
            uploadedBy: MEMBER_ID,
            objectKey: missingKey,
            filename: "lost-original.img",
            contentType: "image/vnd.some-camera", // NOT in RESIZABLE_IMAGE_TYPES either
            thumbnailKey: null,
          },
        ])
        .returning();
      const heicId = inserted[0].id;
      const missingId = inserted[1].id;

      const pendingBefore = await countPendingThumbnailBackfill(db as any);
      assert.ok(
        pendingBefore >= 2,
        `(E) countPending must include the two non-fast-list image/* rows (got ${pendingBefore})`,
      );

      // Drain: every pending row either gets stamped or lands in the skip
      // set, so countPending must converge to 0. The chunk budget derives
      // from the measured backlog (the shared table also holds other
      // suites' uploads) instead of a fixed cap that silently rots as the
      // table grows — a fixed 50-chunk cap failed the day the backlog
      // crossed 500 rows.
      const maxChunks = Math.ceil(pendingBefore / COMMS_THUMBNAIL_BACKFILL_CHUNK) + 20;
      for (let i = 0; i < maxChunks; i++) {
        const { processed } = await processThumbnailBackfillChunk(db as any);
        if (processed === 0) break;
      }
      assert.equal(
        await countPendingThumbnailBackfill(db as any),
        0,
        "(E) drain converges: countPending reaches 0 (stamped or skipped)",
      );

      const heicRow = await getAttachmentRow(heicId);
      assert.ok(
        heicRow.thumbnailKey?.startsWith("comms-attachments/thumb/") &&
          heicRow.thumbnailKey.endsWith(".webp"),
        `(E) image/heic row was attempted and stamped (got ${heicRow.thumbnailKey})`,
      );
      const heicThumb = uploadedObjects.get(heicRow.thumbnailKey!);
      assert.ok(heicThumb, "(E) heic row's thumbnail was uploaded");
      const heicMeta = await sharp(heicThumb!.buffer).metadata();
      assert.equal(heicMeta.format, "webp", "(E) heic row's thumbnail is a real webp");
      assert.equal(heicMeta.width, 600, "(E) heic row's thumbnail downscaled to 600px");

      const missingRow = await getAttachmentRow(missingId);
      assert.equal(
        missingRow.thumbnailKey,
        null,
        "(E) missing-original row stays thumbnail-less (best-effort skip, not a crash)",
      );
      assert.ok(
        getThumbnailBackfillSkippedCount() >= 1,
        "(E) missing-original row landed in the skip set (attempted, then logged)",
      );
      console.log(
        "  ✓ backfill attempts EVERY image/% row: non-fast-list heic stamped, missing original skipped with reason",
      );
    }

    // (F) End-to-end serve: the thumbnail key from (A) is served to a channel
    // member via GET /api/comms/attachments/<thumbnailKey>, and a non-member
    // gets 403 on the same key.
    {
      assert.ok(uploadedThumbKey, "(F) needs the thumbnail key captured in (A)");

      const memberRes = await undici.request(
        `${base}/api/comms/attachments/${uploadedThumbKey}`,
      );
      assert.equal(memberRes.statusCode, 200, "(F) member GET of uploaded thumb should 200");
      assert.equal(
        memberRes.headers["content-type"],
        "image/webp",
        "(F) served thumbnail content type is webp",
      );
      const servedBytes = Buffer.from(await memberRes.body.arrayBuffer());
      const storedThumb = uploadedObjects.get(uploadedThumbKey!);
      assert.ok(
        storedThumb && servedBytes.equals(storedThumb.buffer),
        "(F) served bytes are exactly the generated thumbnail bytes",
      );
      const servedMeta = await sharp(servedBytes).metadata();
      assert.equal(servedMeta.format, "webp", "(F) served thumbnail decodes as webp");

      const outsiderApp = makeApp(OUTSIDER_ID);
      const outsiderServer = outsiderApp.listen(0, "127.0.0.1");
      await new Promise<void>((resolve) => outsiderServer.once("listening", resolve));
      try {
        const { port: outsiderPort } = outsiderServer.address() as AddressInfo;
        const outsiderRes = await undici.request(
          `http://127.0.0.1:${outsiderPort}/api/comms/attachments/${uploadedThumbKey}`,
        );
        assert.equal(
          outsiderRes.statusCode,
          403,
          "(F) non-member GET of uploaded thumb must 403",
        );
        await outsiderRes.body.dump();
      } finally {
        await new Promise<void>((resolve) => outsiderServer.close(() => resolve()));
      }
      console.log(
        "  ✓ uploaded thumbnail key served end-to-end to member (200 webp), non-member 403",
      );
    }

    // (G) Prod-action registration contract (Task #3421/#3437) — the CEO
    // registry must expose the backfill as a background-drain action whose
    // description pins the convergence + idempotency semantics the code
    // above just proved (skip-set exclusion, thumbnail_key IS NULL guard).
    {
      const { PROD_ACTIONS } = await import("../server/services/prodActionsRegistry");
      const action = PROD_ACTIONS.find(
        (a: any) => a.id === "backfill_comms_attachment_thumbnails",
      );
      assert.ok(action, "(G) backfill_comms_attachment_thumbnails registered in PROD_ACTIONS");
      assert.match(
        action!.description,
        /thumbnail_key = NULL/,
        "(G) description states the pending predicate",
      );
      assert.match(
        action!.description,
        /skipped, and excluded from the pending count/,
        "(G) description pins skip-set convergence (no perpetual pending)",
      );
      assert.match(
        action!.change,
        /thumbnail_key IS NULL/,
        "(G) change pins the idempotent UPDATE guard",
      );
      assert.match(
        action!.change,
        /comms-attachments\/thumb\//,
        "(G) change pins the shared thumb key prefix",
      );
      assert.equal(typeof action!.apply, "function", "(G) action has an apply()");
      assert.equal(typeof action!.status, "function", "(G) action has a status()");
      console.log(
        "  ✓ prod-action registered with drain semantics (skip-set convergence + NULL-guarded UPDATE)",
      );
    }
  } finally {
    await new Promise<void>((resolve) => server.close(() => resolve()));
    const dispatcher = undici.getGlobalDispatcher();
    await dispatcher.close().catch(() => {});
  }

  console.log("comms-attachment-upload-thumbnail: PASSED");
  process.exit(0);
})().catch((err) => {
  console.error("comms-attachment-upload-thumbnail: FAILED", err);
  process.exit(1);
});
