// Task #3740 — the nobullmarketing.com marketing website.
//
// One deployment, two audiences:
//   - Visitors on the marketing hosts (apex + www, overridable via
//     MARKETING_SITE_HOSTS) get the static marketing bundle — never the OS
//     SPA shell. Unknown marketing URLs get the marketing 404 page.
//   - Every other host (reports.nobullmarketing.com, *.replit.dev, …) is
//     untouched, except for the stable /website-preview path that serves the
//     same bundle so the design can be reviewed before DNS is connected.
//
// Registered in server/index.ts BEFORE helmet and before all SPA static
// layers (early-boot homepage handler, serveStatic catch-all, dev Vite
// middleware), so marketing hosts are decided first. Marketing responses set
// their own relaxed CSP (reCAPTCHA + Vimeo + Spotify embeds, Google Fonts)
// because the OS-wide helmet CSP would block those frames — and helmet never
// runs for requests this module terminates.
//
// The bundle is committed at website/public (generated by
// `npx tsx website/generate.ts`) and copied to dist/website by script/build.ts
// for production. All internal links inside the bundle are RELATIVE so the
// same files work at the domain root and under /website-preview/.

import express, {
  type Express,
  type Request,
  type Response,
  Router,
} from "express";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

export const MARKETING_PREVIEW_PATH = "/website-preview";

const DEFAULT_MARKETING_HOSTS = "nobullmarketing.com,www.nobullmarketing.com";
const LEGACY_EPISODE_13_PATH = "/resource/episode-13/";
const CANONICAL_EPISODE_13_PATH =
  "/resource/episode-13-interview-with-brita-long-founder-of-the-happier-attorney-llc/";

const RETIRED_CONVERSION_PATHS = new Map([
  ["/book-free-demo/", "booking"],
  ["/contact/", "contact"],
] as const);
/** Marketing hostnames (lowercase). First entry is the canonical apex. */
export function getMarketingHostnames(): string[] {
  return (process.env.MARKETING_SITE_HOSTS || DEFAULT_MARKETING_HOSTS)
    .split(",")
    .map((s) => s.trim().toLowerCase())
    .filter((s) => s.length > 0);
}

export function getMarketingApexHostname(): string {
  return getMarketingHostnames()[0] ?? "nobullmarketing.com";
}

export function isMarketingHost(hostname: string | undefined | null): boolean {
  if (!hostname) return false;
  return getMarketingHostnames().includes(hostname.trim().toLowerCase());
}

/**
 * Hostname of the incoming request, independent of Express's `trust proxy`
 * setting (which is only configured later in bootstrap by setupAuth). Replit's
 * proxy forwards the original host in X-Forwarded-Host; direct requests carry
 * it in Host. Port suffixes are stripped, value lowercased.
 */
export function requestHostname(req: Request): string {
  const xf = req.headers["x-forwarded-host"];
  const raw =
    (Array.isArray(xf) ? xf[0] : xf)?.split(",")[0]?.trim() ||
    req.headers.host ||
    "";
  return raw.replace(/:\d+$/, "").toLowerCase();
}

function resolveModuleDir(): string {
  // Bundled CJS production build (dist/index.cjs): __dirname === dist/.
  if (typeof __dirname !== "undefined") return __dirname;
  // Dev under tsx (ESM): this file lives at server/website/.
  return path.dirname(fileURLToPath(import.meta.url));
}

/** Locate the static bundle in dev (website/public) or prod (dist/website). */
export function resolveMarketingBundleDir(): string | null {
  const moduleDir = resolveModuleDir();
  const candidates = [
    path.resolve(moduleDir, "website"), // prod: dist/website
    path.resolve(moduleDir, "..", "..", "website", "public"), // dev: <ws>/website/public
    path.resolve(process.cwd(), "website", "public"),
    path.resolve(process.cwd(), "dist", "website"),
  ];
  for (const dir of candidates) {
    if (
      fs.existsSync(path.join(dir, "index.html")) &&
      fs.existsSync(path.join(dir, "404.html"))
    ) {
      return dir;
    }
  }
  return null;
}

// Frame hosts used by the bundle: Google reCAPTCHA, Vimeo lightbox + direct embeds,
// Spotify podcast embeds (article bodies), YouTube kept for future article
// embeds. Calendly is a normal external navigation, not an embedded surface.
function marketingCsp(frameAncestors: string): string {
  return [
    "default-src 'self'",
    "script-src 'self' 'unsafe-inline' https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://js.stripe.com",
    // use.typekit.net/p.typekit.net: Adobe Fonts kit (Sweet Sans Pro) used by
    // the redesigned homepage.
    "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://use.typekit.net https://p.typekit.net",
    "font-src 'self' https://fonts.gstatic.com https://use.typekit.net https://p.typekit.net data:",
    "img-src 'self' data: https:",
    "frame-src https://api.leadconnectorhq.com https://player.vimeo.com https://open.spotify.com https://www.youtube.com https://www.youtube-nocookie.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://js.stripe.com https://hooks.stripe.com",
    "connect-src 'self' https://vimeo.com https://*.vimeo.com https://www.google.com/recaptcha/ https://api.stripe.com https://q.stripe.com https://m.stripe.network",
    "media-src 'self' https:",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    `frame-ancestors ${frameAncestors}`,
  ].join("; ");
}

const MARKETING_FRAME_ANCESTORS = "'self'";
// Preview is viewed inside the Replit workspace iframe — mirror the helmet
// frame-ancestors allowances of the OS app.
const PREVIEW_FRAME_ANCESTORS =
  "'self' https://*.replit.dev https://*.replit.com https://*.repl.co";

function setMarketingHeaders(
  res: Response,
  opts: { frameAncestors: string; noindex?: boolean },
): void {
  res.setHeader("Content-Security-Policy", marketingCsp(opts.frameAncestors));
  res.setHeader("X-Content-Type-Options", "nosniff");
  res.setHeader("Referrer-Policy", "strict-origin-when-cross-origin");
  if (opts.noindex) res.setHeader("X-Robots-Tag", "noindex, nofollow");
}

interface SitemapPage {
  path: string;
  title: string;
  priority: string;
}

function buildSitemapXml(origin: string, pages: SitemapPage[]): string {
  const urls = pages
    .map(
      (p) =>
        `  <url><loc>${origin}/${p.path}</loc><priority>${p.priority}</priority></url>`,
    )
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`;
}

function bundleStatic(dir: string) {
  return express.static(dir, {
    index: "index.html",
    redirect: true, // /about -> /about/ so relative links resolve
    fallthrough: true,
    setHeaders: (res, filePath) => {
      if (filePath.endsWith(".html")) {
        res.setHeader("Cache-Control", "no-cache");
      } else {
        res.setHeader("Cache-Control", "public, max-age=86400");
      }
    },
  });
}

function retiredConversionLocation(req: Request, homepage: string): string | null {
  const slashPath = req.path.endsWith("/") ? req.path : `${req.path}/`;
  const fragment = RETIRED_CONVERSION_PATHS.get(
    slashPath as "/book-free-demo/" | "/contact/",
  );
  if (!fragment) return null;

  let search = "";
  try {
    search = new URL(req.originalUrl, "https://marketing.invalid").search;
  } catch {
    // A malformed query must never be reflected into Location. The fixed
    // homepage destination remains safe and useful without it.
  }
  return `${homepage}${search}#${fragment}`;
}
const INTERNAL_BUNDLE_FILES = new Set([
  "/404.html",
  "/sitemap-pages.json",
  "/build-manifest.json",
]);

export function registerMarketingSite(app: Express): void {
  const bundleDir = resolveMarketingBundleDir();
  if (!bundleDir) {
    console.error(
      "[MarketingSite] website bundle not found (looked for website/public + dist/website) — marketing hosts and /website-preview are disabled",
    );
    return;
  }

  const notFoundTemplate = fs.readFileSync(
    path.join(bundleDir, "404.html"),
    "utf8",
  );
  let sitemapPages: SitemapPage[] = [];
  try {
    sitemapPages = JSON.parse(
      fs.readFileSync(path.join(bundleDir, "sitemap-pages.json"), "utf8"),
    ) as SitemapPage[];
  } catch (err) {
    console.error(
      "[MarketingSite] sitemap-pages.json missing/unreadable — sitemap.xml will be empty:",
      err,
    );
  }

  const sendMarketing404 = (res: Response, baseHref: string): void => {
    res
      .status(404)
      .type("html")
      .setHeader("Cache-Control", "no-cache");
    res.send(notFoundTemplate.replaceAll("{{BASE}}", baseHref));
  };

  const marketingStatic = bundleStatic(bundleDir);

  // ── Marketing hosts: apex + www ─────────────────────────────────────────
  app.use((req, res, next) => {
    const host = requestHostname(req);
    if (!isMarketingHost(host)) return next();

    // API stays host-agnostic: the homepage inquiry form posts to
    // /api/website/inquiry from the marketing domain itself.
    if (req.path === "/api" || req.path.startsWith("/api/")) return next();

    // Alias hosts (www.) permanently redirect to the apex.
    const apex = getMarketingApexHostname();
    if (host !== apex) {
      return res.redirect(301, `https://${apex}${req.originalUrl}`);
    }

    setMarketingHeaders(res, { frameAncestors: MARKETING_FRAME_ANCESTORS });

    if (req.method !== "GET" && req.method !== "HEAD") {
      return sendMarketing404(res, "/");
    }
    const retiredLocation = retiredConversionLocation(req, "/");
    if (retiredLocation) {
      return res.redirect(301, retiredLocation);
    }
    if (req.path === LEGACY_EPISODE_13_PATH) {
      return res.redirect(301, CANONICAL_EPISODE_13_PATH);
    }
    if (req.path === "/sitemap.xml") {
      res.type("application/xml").setHeader("Cache-Control", "no-cache");
      return res.send(buildSitemapXml(`https://${apex}`, sitemapPages));
    }
    if (req.path === "/robots.txt") {
      res.type("text/plain").setHeader("Cache-Control", "no-cache");
      return res.send(
        `User-agent: *\nAllow: /\n\nSitemap: https://${apex}/sitemap.xml\n`,
      );
    }
    if (INTERNAL_BUNDLE_FILES.has(req.path)) {
      return sendMarketing404(res, "/");
    }
    // Static bundle; anything it can't resolve is a marketing 404 — never
    // the OS SPA shell.
    return marketingStatic(req, res, () => sendMarketing404(res, "/"));
  });

  // ── Pre-DNS preview path on all other hosts ─────────────────────────────
  const preview = Router();
  preview.use((req, res, next) => {
    setMarketingHeaders(res, {
      frameAncestors: PREVIEW_FRAME_ANCESTORS,
      noindex: true, // never index the preview copy on the OS hosts
    });
    if (
      (req.method === "GET" || req.method === "HEAD") &&
      req.path === LEGACY_EPISODE_13_PATH
    ) {
      return res.redirect(
        301,
        `${MARKETING_PREVIEW_PATH}${CANONICAL_EPISODE_13_PATH}`,
      );
    }
    if (req.method === "GET" || req.method === "HEAD") {
      const retiredLocation = retiredConversionLocation(
        req,
        `${MARKETING_PREVIEW_PATH}/`,
      );
      if (retiredLocation) {
        return res.redirect(301, retiredLocation);
      }
    }
    if (INTERNAL_BUNDLE_FILES.has(req.path)) {
      return sendMarketing404(res, `${MARKETING_PREVIEW_PATH}/`);
    }
    next();
  });
  preview.use(marketingStatic);
  preview.use((_req, res) => {
    sendMarketing404(res, `${MARKETING_PREVIEW_PATH}/`);
  });
  app.use(MARKETING_PREVIEW_PATH, preview);

  console.log(
    `[MarketingSite] bundle ${bundleDir} — hosts [${getMarketingHostnames().join(", ")}], preview at ${MARKETING_PREVIEW_PATH}`,
  );
}
