export const ACTIVITY_FLUSH_INTERVAL_MS = 30_000;
export const ACTIVITY_MAX_EVENTS_PER_FLUSH = 50;
export const ACTIVITY_MAX_BUFFERED_EVENTS = 200;
export const ACTIVITY_EVENT_COALESCE_WINDOW_MS = 5_000;
