import { CANONICAL_PRODUCTS, type CanonicalProduct } from "./productResolution";
import { readGbpLeadQuality } from "./activeProductsHeadline";

/**
 * Mapping from a canonical product to the marketing-block keys that hold its
 * platform-specific data. Both parser-output shape (`gbpLocations`) and stored
 * section shape (`gbp.locations`, `gbpLeadQuality`) are covered so a single
 * filter call works at every chokepoint (PDF parse, webhook write, reimport
 * write, section PUT, public read sanitizer).
 */
// Note: "other" is intentionally NOT mapped to any marketing keys.
// `otherLeads` (Social Media / Direct Calls / Referrals lead counts) is
// general lead reporting that should always render regardless of which
// products the firm has signed up for — the firm doesn't pay us to manage
// it, but the leads still flow into their pipeline. The structural filter
// below therefore never deletes `otherLeads` / `other`. The Lead Quality
// headline (computeQualityHeadline + aggregateActiveLeadQuality) separately
// excludes Other's leadQuality contribution because we don't control the
// quality of leads we didn't generate.
export const PRODUCT_TO_MARKETING_KEYS: Record<CanonicalProduct, string[]> = {
  gbp: ["gbp", "gbpLocations", "gbpLeadQuality"],
  google_ads: ["googleAds"],
  lsa: ["lsa"],
  webinar: ["webinar", "webinars"],
  other: [],
};

/**
 * Build a fresh, zeroed Lead Quality aggregate from `marketing` that ONLY sums
 * platforms in the active set, plus the always-on `otherLeads` bucket (which
 * is a lead-source category, not a tracked product). Use this anywhere the
 * webhook/import path used to compute `allLeadQuality` by hand — that older
 * inline sum included inactive-product Lead Quality and was the structural
 * source of the Wanta Thome 30% headline bug.
 */
export function aggregateActiveLeadQuality(
  marketing: any,
  activeProducts: CanonicalProduct[],
  opts: { includeWebinar?: boolean } = {},
): { good: number; notQuotable: number; missedCalls: number; noData: number } {
  const out = { good: 0, notQuotable: 0, missedCalls: 0, noData: 0 };
  if (!marketing) return out;
  const active = new Set(activeProducts);
  const add = (lq: any) => {
    if (!lq) return;
    out.good += Number(lq.good) || 0;
    out.notQuotable += Number(lq.notQuotable) || 0;
    out.missedCalls += Number(lq.missedCalls) || 0;
    out.noData += Number(lq.noData) || 0;
  };
  if (active.has("gbp")) {
    // Task #3771: canonical GBP reader (rollup-first, per-location-sum
    // fallback) shared with `computeQualityHeadline` and the public
    // renderer, so the persisted aggregate can never disagree with the
    // rendered Leads Quality Breakdown card. The webhook/reparse write
    // paths derive the rollup FROM locations right before calling this, so
    // ingest-time aggregates are unchanged; only divergent stored data
    // (e.g. a manual aggregate edit) now resolves to the rollup everywhere
    // instead of to a different shape per consumer.
    add(readGbpLeadQuality(marketing).counts);
  }
  if (active.has("google_ads")) add(marketing.googleAds?.leadQuality);
  if (active.has("lsa")) add(marketing.lsa?.leadQuality);
  if (active.has("webinar") && opts.includeWebinar !== false) {
    add(marketing.webinar?.leadQuality);
  }
  // Task #1028 (clarification): Other's leadQuality is NEVER part of the
  // headline Lead Quality % — those leads aren't generated by us so we
  // don't measure their quality. Other lead counts still render in the
  // general lead-reporting card; only the Lead Quality headline excludes
  // them.
  return out;
}

export interface FilterContext {
  source: string;
  clientId?: string;
  reportId?: string;
}

export interface FilterResultEntry {
  product: CanonicalProduct;
  key: string;
  hadData: boolean;
}

export interface FilterResult {
  marketing: Record<string, any>;
  removed: FilterResultEntry[];
}

const ZERO_LQ = { good: 0, notQuotable: 0, missedCalls: 0, noData: 0 } as const;

function blockHasData(block: any): boolean {
  if (block == null) return false;
  if (Array.isArray(block)) return block.length > 0;
  if (typeof block !== "object") return Boolean(block);
  for (const v of Object.values(block)) {
    if (v == null) continue;
    if (typeof v === "number" && v !== 0) return true;
    if (typeof v === "string" && v.trim() !== "") return true;
    if (Array.isArray(v) && v.length > 0) return true;
    if (typeof v === "object" && blockHasData(v)) return true;
  }
  return false;
}

function emptyForKey(key: string): any {
  switch (key) {
    case "gbp": return { locations: [], shared: {} };
    case "gbpLocations": return [];
    case "gbpLeadQuality": return { ...ZERO_LQ };
    case "googleAds":
    case "lsa":
      return { uniqueLeads: 0, adSpend: 0, costPerLead: 0, leadQuality: { ...ZERO_LQ } };
    case "webinar":
    case "webinars":
      return { registrants: 0, attendees: 0, hotTransfers: 0, showRate: 0, hotTransferRate: 0, leadQuality: { ...ZERO_LQ } };
    default:
      return null;
  }
}

/**
 * Structural Active-Products gate (Task #1028). Drops every platform block in
 * `marketing` whose canonical product is NOT in `activeProducts`. The marketing
 * object is mutated in place and returned for caller convenience; the returned
 * `removed` array is a per-key audit log suitable for structured logging.
 *
 * Use this at every write boundary (parser output, webhook section write,
 * reimport, section PUT) AND defensively on the public-read sanitizer so the
 * rendered surface can never display data for a product the client doesn't own.
 */
export function applyActiveProductsFilter(
  marketing: any,
  activeProducts: CanonicalProduct[],
  ctx: FilterContext = { source: "unknown" },
): FilterResult {
  const removed: FilterResultEntry[] = [];
  if (!marketing || typeof marketing !== "object") {
    return { marketing: marketing ?? {}, removed };
  }
  const active = new Set(activeProducts);
  for (const product of CANONICAL_PRODUCTS) {
    if (active.has(product)) continue;
    for (const key of PRODUCT_TO_MARKETING_KEYS[product]) {
      if (!(key in marketing)) continue;
      const had = blockHasData(marketing[key]);
      removed.push({ product, key, hadData: had });
      // Task #1028: actually delete inactive platform keys instead of
      // zero-ing them. Renderers all use optional chaining, so deletion is
      // safe and removes ghost-block structural noise from stored JSON.
      delete marketing[key];
    }
  }
  if (removed.some(r => r.hadData)) {
    // eslint-disable-next-line no-console
    console.log(
      `[ActiveProductsFilter] source=${ctx.source} client=${ctx.clientId ?? "-"} report=${ctx.reportId ?? "-"} ` +
      `active=${activeProducts.join(",") || "(none)"} removed=${JSON.stringify(removed.filter(r => r.hadData))}`,
    );
  }
  return { marketing, removed };
}
