/**
 * Task #4115 — Post-merge auto-refresh for the REMAINING committed generated
 * artifacts with freshness lints (generalizing Task #4111's route-inventory
 * hook to the other two artifacts that can silently go stale after merges):
 *
 *   1. audits/D-endpoint-contract-table.{md,json}
 *      Generated FROM tests/route-inventory.json by
 *      scripts/generate-endpoint-contract-table.mjs. Merge-shifted drift is
 *      not just possible — the Task #4111 route-inventory auto-refresh
 *      CREATES it: when that hook regenerates the inventory (handler
 *      file:line moved), the contract table's handler column immediately
 *      goes stale, and lint-contract-table-freshness turns red on every
 *      nightly until someone regenerates by hand (exactly what happened
 *      twice on 2026-08-08). This hook therefore MUST run after the
 *      route-inventory refresh in scripts/post-merge.sh.
 *
 *   2. website/public (marketing bundle, stamped build-manifest.json)
 *      Generated by `npx tsx website/generate.ts`; the freshness lint
 *      compares a content fingerprint of the inputs against the committed
 *      stamp. Two tasks that each edit different website inputs and each
 *      regenerate can merge cleanly while neither side's stamp matches the
 *      UNION of inputs — silent post-merge staleness.
 *
 *   3. (Task #4189) The four generated governance inventories in
 *      audits/governance/ — data-ownership.json, integration-reliability.json,
 *      async-topology.json, test-portfolio-baseline.json — freshness-guarded
 *      by the tests/governance-*-inventory.test.ts smoke tests. Same
 *      parallel-merge failure mode as the route inventory: each branch fresh
 *      alone, stale after the merge union. Their `--check` is
 *      checkArtifact(committed, generate()) from governanceInventoryLib, so
 *      the hook drives those exact functions in-process (no re-implemented
 *      comparison). None of the four is generated from another artifact —
 *      no derived-artifact chaining.
 *
 * Same contract as scripts/post-merge-route-inventory-refresh.ts:
 *   - reuses each lint's exported runLint() (never re-implements the check);
 *   - on staleness runs the real generator, re-lints, and commits ONLY the
 *     artifact paths (`git add -- <paths>` + `git commit --only -- <paths>`,
 *     --no-verify, inline -c user.* identity);
 *   - a lint still red after regen commits the (accurate) regenerated
 *     artifacts anyway but exits 1 so post-merge.sh warns loudly;
 *   - exit 0 = all artifacts fresh or auto-refreshed clean; 1 = needs human
 *     attention. post-merge.sh treats failure as a loud non-fatal warning —
 *     the gate/nightly lints stay the authoritative enforcement.
 */

import { spawnSync } from "node:child_process";
import { runLint as runContractTableLint } from "./lint-contract-table-freshness";
import { runLint as runWebsiteBundleLint } from "./lint-website-bundle-freshness";
import { checkArtifact, type InventoryDocument } from "./governanceInventoryLib";
import {
  generate as generateDataOwnership,
  ARTIFACT_PATH as DATA_OWNERSHIP_PATH,
} from "./generate-data-ownership-inventory";
import {
  generate as generateIntegrationReliability,
  ARTIFACT_PATH as INTEGRATION_RELIABILITY_PATH,
} from "./generate-integration-reliability-inventory";
import {
  generate as generateAsyncTopology,
  ARTIFACT_PATH as ASYNC_TOPOLOGY_PATH,
} from "./generate-async-topology-inventory";
import {
  generate as generateTestPortfolio,
  ARTIFACT_PATH as TEST_PORTFOLIO_PATH,
} from "./generate-test-portfolio-baseline";

/** Minimal lint-result shape shared by every freshness lint we drive. */
export interface FreshnessLintResult {
  ok: boolean;
  problems: string[];
}

export interface ArtifactSpec {
  /** Short slug used in log lines. */
  name: string;
  /** Exact repo-relative paths staged + committed on refresh. */
  paths: readonly string[];
  /** Human-facing regen command, quoted in failure messages. */
  regenCommand: string;
  commitMessage: string;
}

/**
 * Task #4189 — freshness check for a governance inventory: the generators
 * have no separate lint module; `--check` IS `checkArtifact(committed,
 * generate())` (see scripts/governanceInventoryLib.ts runGeneratorCli), so we
 * call the exact same functions in-process rather than re-implementing the
 * comparison. A generate() throw (e.g. an orphaned override key — a source
 * problem regen cannot fix) is reported as a red result, which routes to the
 * loud-warn exit-1 path.
 */
function governanceLint(artifactPath: string, generate: () => InventoryDocument): FreshnessLintResult {
  try {
    return checkArtifact(artifactPath, generate());
  } catch (err) {
    return {
      ok: false,
      problems: [`generation failed: ${err instanceof Error ? err.message : String(err)}`],
    };
  }
}

export const ARTIFACTS: readonly (ArtifactSpec & {
  lint: () => FreshnessLintResult;
  regenArgv: readonly [string, ...string[]];
})[] = [
  {
    name: "endpoint-contract-table",
    paths: ["audits/D-endpoint-contract-table.md", "audits/D-endpoint-contract-table.json"],
    regenCommand: "node scripts/generate-endpoint-contract-table.mjs",
    regenArgv: ["node", "scripts/generate-endpoint-contract-table.mjs"],
    commitMessage:
      "post-merge: auto-regenerate endpoint contract table (merge-shifted drift, Task #4115)",
    lint: () => runContractTableLint(),
  },
  {
    name: "website-bundle",
    paths: ["website/public"],
    regenCommand: "npx tsx website/generate.ts",
    regenArgv: ["npx", "tsx", "website/generate.ts"],
    commitMessage:
      "post-merge: auto-regenerate marketing website bundle (merge-shifted drift, Task #4115)",
    lint: () => runWebsiteBundleLint(),
  },
  // Task #4189 — the four generated governance inventories
  // (audits/governance/*, freshness-guarded by the
  // tests/governance-*-inventory.test.ts smoke tests). Two branches can each
  // be fresh alone yet stale after the merge (the route-inventory failure
  // mode); regen self-heals the merged union. None of the four is generated
  // FROM another artifact, so their relative order is free — they sit after
  // the contract table only to keep the #4115 route-inventory→contract-table
  // dependency chain contiguous above.
  {
    name: "governance-data-ownership",
    paths: [DATA_OWNERSHIP_PATH],
    regenCommand: "npx tsx scripts/generate-data-ownership-inventory.ts",
    regenArgv: ["npx", "tsx", "scripts/generate-data-ownership-inventory.ts"],
    commitMessage:
      "post-merge: auto-regenerate governance data-ownership inventory (merge-shifted drift, Task #4189)",
    lint: () => governanceLint(DATA_OWNERSHIP_PATH, generateDataOwnership),
  },
  {
    name: "governance-integration-reliability",
    paths: [INTEGRATION_RELIABILITY_PATH],
    regenCommand: "npx tsx scripts/generate-integration-reliability-inventory.ts",
    regenArgv: ["npx", "tsx", "scripts/generate-integration-reliability-inventory.ts"],
    commitMessage:
      "post-merge: auto-regenerate governance integration-reliability inventory (merge-shifted drift, Task #4189)",
    lint: () => governanceLint(INTEGRATION_RELIABILITY_PATH, generateIntegrationReliability),
  },
  {
    name: "governance-async-topology",
    paths: [ASYNC_TOPOLOGY_PATH],
    regenCommand: "npx tsx scripts/generate-async-topology-inventory.ts",
    regenArgv: ["npx", "tsx", "scripts/generate-async-topology-inventory.ts"],
    commitMessage:
      "post-merge: auto-regenerate governance async-topology inventory (merge-shifted drift, Task #4189)",
    lint: () => governanceLint(ASYNC_TOPOLOGY_PATH, generateAsyncTopology),
  },
  {
    name: "governance-test-portfolio-baseline",
    paths: [TEST_PORTFOLIO_PATH],
    regenCommand: "npx tsx scripts/generate-test-portfolio-baseline.ts",
    regenArgv: ["npx", "tsx", "scripts/generate-test-portfolio-baseline.ts"],
    commitMessage:
      "post-merge: auto-regenerate governance test-portfolio baseline (merge-shifted drift, Task #4189)",
    lint: () => governanceLint(TEST_PORTFOLIO_PATH, generateTestPortfolio),
  },
];

export interface RefreshDeps {
  lint: () => FreshnessLintResult;
  regen: () => boolean;
  commit: () => "committed" | "nothing-to-commit" | "failed";
  log: (line: string) => void;
}

export interface RefreshResult {
  outcome:
    | "fresh"
    | "refreshed-committed"
    | "refreshed-nothing-to-commit"
    | "regen-failed"
    | "commit-failed"
    | "still-stale-after-regen";
  exitCode: 0 | 1;
  problemsBefore: string[];
  problemsAfter: string[];
}

/**
 * Decision core, unit-testable with injected deps: lint → (stale?) regen →
 * re-lint → commit. Identical semantics to the Task #4111 route-inventory
 * core. Never throws.
 */
export function refreshArtifactIfStale(spec: ArtifactSpec, deps: RefreshDeps): RefreshResult {
  const tag = `[generated-artifact-refresh:${spec.name}]`;
  const before = deps.lint();
  if (before.ok) {
    deps.log(`${tag} OK — committed artifact matches its inputs; nothing to do.`);
    return { outcome: "fresh", exitCode: 0, problemsBefore: [], problemsAfter: [] };
  }

  deps.log(`${tag} STALE after merge — ${before.problems.length} problem(s):`);
  for (const p of before.problems) deps.log(`  - ${p}`);
  deps.log(
    `${tag} auto-running \`${spec.regenCommand}\` (merge-shifted drift would otherwise turn every nightly run red until someone regenerates by hand) …`,
  );

  if (!deps.regen()) {
    deps.log(
      `${tag} !!! regen FAILED — artifact is still stale; the nightly lint WILL be red. Run \`${spec.regenCommand}\` by hand and commit ${spec.paths.join(" + ")}.`,
    );
    return {
      outcome: "regen-failed",
      exitCode: 1,
      problemsBefore: before.problems,
      problemsAfter: before.problems,
    };
  }

  const after = deps.lint();
  // Commit the refreshed artifacts regardless of remaining problems: a
  // regenerated artifact is accurate even when a source bug keeps the lint
  // red (regen cannot fix the source).
  const commitOutcome = deps.commit();
  if (commitOutcome === "failed") {
    deps.log(
      `${tag} !!! COMMIT FAILED — the regenerated artifact is only in the worktree. Commit ${spec.paths.join(" + ")} by hand or the refresh is lost on the next clean checkout.`,
    );
    return {
      outcome: "commit-failed",
      exitCode: 1,
      problemsBefore: before.problems,
      problemsAfter: after.problems,
    };
  }

  if (!after.ok) {
    deps.log(
      `${tag} !!! STILL FAILING after regen — ${after.problems.length} problem(s) regen cannot fix (fix the SOURCE):`,
    );
    for (const p of after.problems) deps.log(`  - ${p}`);
    return {
      outcome: "still-stale-after-regen",
      exitCode: 1,
      problemsBefore: before.problems,
      problemsAfter: after.problems,
    };
  }

  if (commitOutcome === "nothing-to-commit") {
    deps.log(
      `${tag} refreshed — artifact now fresh; files already matched HEAD, nothing to commit.`,
    );
    return {
      outcome: "refreshed-nothing-to-commit",
      exitCode: 0,
      problemsBefore: before.problems,
      problemsAfter: [],
    };
  }

  deps.log(`${tag} refreshed + committed — artifact fresh again. Nightly freshness lint stays green.`);
  return {
    outcome: "refreshed-committed",
    exitCode: 0,
    problemsBefore: before.problems,
    problemsAfter: [],
  };
}

function run(cmd: string, args: string[]): { ok: boolean; stderr: string } {
  try {
    const res = spawnSync(cmd, args, {
      encoding: "utf8",
      // The contract-table generator scans the whole client/tests corpus for
      // caller lists (~95s measured 2026-08-09); give real headroom.
      timeout: 300_000,
      maxBuffer: 32 * 1024 * 1024,
    });
    return { ok: res.status === 0, stderr: res.stderr ?? "" };
  } catch (err) {
    return { ok: false, stderr: (err as Error).message };
  }
}

function realRegen(spec: (typeof ARTIFACTS)[number]): boolean {
  const [cmd, ...args] = spec.regenArgv;
  const res = run(cmd, args);
  if (!res.ok) {
    console.error(
      `[generated-artifact-refresh:${spec.name}] regen stderr: ${res.stderr.trim().slice(0, 2000)}`,
    );
  }
  return res.ok;
}

function realCommit(spec: ArtifactSpec): "committed" | "nothing-to-commit" | "failed" {
  // Stage ONLY the artifact paths — post-merge worktrees can carry other
  // modifications that must never be swept into this auto-commit.
  const add = run("git", ["add", "--", ...spec.paths]);
  if (!add.ok) {
    console.error(`[generated-artifact-refresh:${spec.name}] git add failed: ${add.stderr.trim()}`);
    return "failed";
  }
  const staged = run("git", ["diff", "--cached", "--quiet", "--", ...spec.paths]);
  if (staged.ok) return "nothing-to-commit"; // exit 0 = no staged changes
  const commit = run("git", [
    "-c",
    "user.name=post-merge generated-artifact refresh",
    "-c",
    "user.email=post-merge@local",
    "commit",
    "--no-verify",
    "-m",
    spec.commitMessage,
    "--only",
    "--",
    ...spec.paths,
  ]);
  if (!commit.ok) {
    console.error(
      `[generated-artifact-refresh:${spec.name}] git commit failed: ${commit.stderr.trim()}`,
    );
    return "failed";
  }
  return "committed";
}

export function cliMain(): number {
  let exitCode = 0;
  for (const spec of ARTIFACTS) {
    const result = refreshArtifactIfStale(spec, {
      lint: spec.lint,
      regen: () => realRegen(spec),
      commit: () => realCommit(spec),
      log: (line) => console.log(line),
    });
    if (result.exitCode !== 0) exitCode = 1;
  }
  return exitCode;
}

const isMain =
  import.meta.url === `file://${process.argv[1]}` ||
  (process.argv[1]?.endsWith("post-merge-generated-artifact-refresh.ts") ?? false);
if (isMain) {
  process.exit(cliMain());
}
